version: "3.9"
services:
  postgres:
    image: "postgres:14.2"
    container_name: "psql"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database-network

  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - database-network
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  database-network: # Name in this docker-compose file
    driver: bridge