version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env
  psql:
    image: "postgres:14.2"
    container_name: "psql"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
